### ISSUE TITLE
stty: stdout appears redirected, but stdin is the control descriptor

### ISSUE THREAD

**Issue by phlind** [huijunchen9260/shbib#1]
Hallo, thanks for writing this interesting script. 

When I want to search for an an entry via the `s` key, the following is displayed:

`stty: stdout appears redirected, but stdin is the control descriptor`

I can still type something though, but I overwrite the prompt message on the bottom.

And whenever I want to save an entry from crossref to the .bib file, nothing happens.

I'm using macOS 11 with zsh.

EDIT: Running it with `bash ./shbib` results the same. When I run it with `dash ./shbib` though, I still get the error mentioned above, but writing to the `.bib` file works.

**Comment by huijunchen9260** [comment]
Wow! Thank you for opening this issue!

Could you first tell me the outcome of following command?

```sh
ls -l /bin/sh
```

Second, zsh is NOT POSIX-compliant! (surprise! Go to [zsh manual](http://zsh.sourceforge.net/Doc/Release/index.html) to see some detail), and thus `set -- $var` will NOT work in zsh. That's why `dash` and `bash` can write into your `$BIB`.

 My way to go through this is to make my `/bin/sh` be either `dash` and `bash` (`dash` is highly recommended though). Since `/bin/sh` is just a symlink for shell, you can rebuild the symlink.

**Please notice that the following command may not work in macOS. Please check whether the above description is suitable for macOS or not before running the following command: **

```sh
sudo rm /bin/sh
ln -s /bin/dash /bin/sh
```
For the second part...I am actually not sure what happened! Could you give me some screenshot or gif so that I can understand that `stty` error better?

**Comment by huijunchen9260** [comment]
Check https://github.com/huijunchen9260/shbib/commit/9a36a4d10b0d637fd81fdb9ce118d67c501ad22e to see whether this issue is solved.
